version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-frontend:
    docker:
      - image: cimg/node:18.7.0
    steps:
      - checkout
      - node/install-yarn
      - run:
          name: "Install dependencies"
          command: "cd ./frontend/ && yarn"
      - run:
          name: "Build frontend"
          command: "cd ./frontend/ && yarn build"

workflows:
  test-build-frontend:
    jobs:
      - build-frontend
